### DISCUSSION TITLE
ESPHome Support on Seeed Studio XIAO ESP32S3 | Seeed Studio Wiki

### DISCUSSION THREAD

**Discussion by giscus** [Seeed-Studio/wiki-documents#1545] [Q&A]
# ESPHome Support on Seeed Studio XIAO ESP32S3 | Seeed Studio Wiki

ESPHome-Support-on-Seeed-Studio-XIAO-ESP32S3

https://wiki.seeedstudio.com/XIAO_ESP32S3_esphome/

**Comment by martijnvwezel** [comment]
Using the exact same yaml almost I still get my camera unavaliable

**Comment by fdbuck0** [comment]
Is there a possibility to adjust camera parameters (exposure, white balance,...) in home assistant/ESPHome?

**Reply by ReKST-117** [reply]
Hi, I think you could refer to ESPHome camera configurations: https://esphome.io/components/esp32_camera.html

**Comment by EnesA20** [comment]
For me with the cam module this worked:

`esphome:
  name: esp32s3
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# PSRAM expliciet aanzetten in octal 80 MHz
psram:
  mode: octal
  speed: 80MHz

# Logging inschakelen
logger:

# Home Assistant‑API inschakelen
api:

# Over‑the‑air‑update inschakelen
ota:

# Wi‑Fi‑configuratie
wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback hotspot activeren als de wifi‑verbinding faalt
  ap:
    ssid: "Esp32-S3-Cam Fallback Hotspot"
    password: "Password123"

# Captive portal configuratie
captive_portal:

i2c:
  - id: camera_i2c
    sda: GPIO40
    scl: GPIO39
    frequency: 400kHz

# Configuratie voor de ESP32‑camera
esp32_camera:
  id: espcam
  name: My Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  resolution: 800x600   # SVGA
  jpeg_quality: 28
  frame_buffer_count: 2
  # optioneel eerst testen met lagere resolutie:
  # resolution: 640x480  # VGA

# Low-Light Best Performance
#  aec_mode: auto
 # aec2: true
 # ae_level: 2  

#  agc_mode: auto
#  agc_gain_ceiling: 128x
#  wb_mode: auto  

  brightness: 1            # -2..+2
  contrast: 1              # -2..+2
  saturation: -1           # -2..+2, iets lager dempt ruisachtig kleurzwabberen

# Webserver voor de camera
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

**Reply by EnesA20** [reply]
```
esphome:
  name: esp32s3
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# PSRAM expliciet aanzetten in octal 80 MHz
psram:
  mode: octal
  speed: 80MHz

# Logging inschakelen
logger:

# Home Assistant‑API inschakelen
api:

# Over‑the‑air‑update inschakelen
ota:

# Wi‑Fi‑configuratie
wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback hotspot activeren als de wifi‑verbinding faalt
  ap:
    ssid: "Esp32-S3-Cam Fallback Hotspot"
    password: "BfnntuzN9G3t"

# Captive portal configuratie
captive_portal:

i2c:
  - id: camera_i2c
    sda: GPIO40
    scl: GPIO39
    frequency: 400kHz

# Configuratie voor de ESP32‑camera
esp32_camera:
  id: espcam
  name: My Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  resolution: 800x600   # SVGA
  jpeg_quality: 28
  frame_buffer_count: 2
  # optioneel eerst testen met lagere resolutie:
  # resolution: 640x480  # VGA

  aec_mode: auto
  aec2: true
  ae_level: 2  

  agc_mode: auto
  agc_gain_ceiling: 128x
  wb_mode: auto  

  brightness: 1            # -2..+2
  contrast: 1              # -2..+2
  saturation: -1           # -2..+2, iets lager dempt ruisachtig kleurzwabberen

# Webserver voor de camera
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
```
