### DISCUSSION TITLE
Voice Assistant System for Home Assitant | Seeed Studio Wiki

### DISCUSSION THREAD

**Discussion by giscus** [Seeed-Studio/wiki-documents#1609] [Q&A]
# Voice Assistant System for Home Assitant | Seeed Studio Wiki

Voice Assistant System for Home Assitant

https://wiki.seeedstudio.com/respeaker_lite_ha/

**Comment by gangoke** [comment]
How to get esphome media_player working?

**Reply by jerryyip** [reply]
Thanks to @formatBCE, you can find a wonderful esphome yaml (with media_player of course) in his [repo](https://community.home-assistant.io/t/respeaker-lite-new-seeed-studio-voice-assistant-development-kit-hardware-combine-esp32-with-xmos-xu316-dsp-chip-for-advanced-audio-processing-as-a-esphome-based-home-assistant-assist-satellite-voice-devkit/756944/246?)

**Comment by jastBytes** [comment]
My speaker seems to reboot constantly and giving a crackling sound when it does. It connects to HA and disconnects again and again. Is that a knwon problem? The logs in ESPHome don't show any hint whats the issue.

**Reply by jastBytes** [reply]
I found the error log but don't know how to fix:

```
[12:55:30][D][voice_assistant:510]: State changed from IDLE to START_MICROPHONE
[12:55:30][D][voice_assistant:516]: Desired state set to START_PIPELINE
[12:55:30][D][light:036]: 'ReSpeakerv3' Setting:
[12:55:30][D][voice_assistant:222]: Starting Microphone
[12:55:30]Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
[12:55:30]
[12:55:30]Core  1 register dump:
[12:55:30]PC      : 0x400570af  PS      : 0x00060a30  A0      : 0x82011fc1  A1      : 0x3fcedec0  
[12:55:30]A2      : 0xa5a5a5a5  A3      : 0x00000000  A4      : 0x00000400  A5      : 0xa5a5a5a5  
[12:55:30]A6      : 0x3fcaf900  A7      : 0x00000000  A8      : 0x00000040  A9      : 0x3fcede40  
[12:55:30]A10     : 0x3fcee30c  A11     : 0x00000005  A12     : 0x8037c3d8  A13     : 0x3fc98270  
[12:55:30]A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001d  
[12:55:30]EXCVADDR: 0xa5a5a5a5  LBEG    : 0x40056f08  LEND    : 0x40056f12  LCOUNT  : 0x00000000  
[12:55:30]
[12:55:30]
[12:55:30]Backtrace: 0x400570ac:0x3fcedec0 0x42011fbe:0x3fceded0 0x42012d78:0x3fcedef0 0x42081b99:0x3fcedfa0 0x42081be5:0x3fcedfc0 0x42016ad0:0x3fcedfe0 0x420195f6:0x3fcee010 0x4200b3f2:0x3fcee030
[12:55:30]
[12:55:30]
[12:55:30]
[12:55:30]
[12:55:30]ELF file SHA256: 582573910116efa7
[12:55:30]
[12:55:30]Rebooting...
```

**Reply by jerryyip** [reply]
Could you please put the backtrace and your ELF file to https://maximeborges.github.io/esp-stacktrace-decoder/ to decode the stack? And are you using the same yaml file as our wiki?

**Reply by jastBytes** [reply]
It was a problem with ESPHome. Updating it helped. It works now.

**Comment by alpaygani** [comment]
Even though I followed all the steps, I cannot see my "respeaker lite" device with web.esphome. 
I don't have a device showing as "USB/Jtag" in the device list. 
I am using 
- Windows 11 (64bit) 
- Chrome browser 
I installed "respeaker_lite_i2s_dfu_firmware_v1.0.7.bin" firmware on Respeaker Lite via esp-idf. I also installed the (Winusb V6...) drivers via Zadgi. I tried all of this on 3 different computers. Still I can't see my device in the comport section.
Please help on this matter. 
Thank you very much.

**Reply by jerryyip** [reply]
The `respeaker_lite_i2s_dfu_firmware_v1.0.7.bin` firmware is for the XMOS chip, not the ESP32S3. It should be installed with `dfu-util` tool.
Both XMOS chip and XIAO ESP32S3 need to flash/update their firmware.
This guide is just for XMOS chip firmware updates: https://github.com/respeaker/ReSpeaker_Lite/blob/master/xmos_firmwares/dfu_guide.md 
And these steps are for XIAO ESP32S3 ESPhome firmware installation:
https://wiki.seeedstudio.com/respeaker_lite_ha/#add-xiao-esp32s3-to-esphome
Thanks to the community we have some perfect video guides too:
https://www.youtube.com/watch?v=XjUeJh2Ok3o&t=1s

**Comment by thematrixdev** [comment]
If I want to use the 3.5mm jack to output audio, rather than the jumper, do I need to modify anything?

**Reply by formatBCE** [reply]
It works automatically, just insert jack

**Comment by Richard-Regan** [comment]
Hi,
When I run the downloaded YAML, I get errors as shown below:
NFO ESPHome 2024.12.1
INFO Reading configuration /config/esphome/respeaker-s3.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing esp32s3 (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Reading CMake configuration...
Generating assembly for certificate bundle...
Warning! Flash memory size mismatch detected. Expected 4MB, found 2MB!
Please select a proper value in your `sdkconfig.defaults` or via the `menuconfig` target!
No dependencies
Compiling .pioenvs/esp32s3/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/esp32s3/src/esphome/components/esp32_rmt_led_strip/led_strip.cpp.o
In file included from src/esphome/components/esp32_rmt_led_strip/led_strip.h:12,
                 from src/esphome/components/esp32_rmt_led_strip/led_strip.cpp:2:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
Compiling .pioenvs/esp32s3/src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.cpp.o
In file included from src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.h:5,
                 from src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
Compiling .pioenvs/esp32s3/src/esphome/components/i2s_audio_xiao/microphone/i2s_audio_microphone.cpp.o
In file included from src/esphome/components/i2s_audio_xiao/microphone/../i2s_audio_xiao.h:5,
                 from src/esphome/components/i2s_audio_xiao/microphone/i2s_audio_microphone.h:5,
                 from src/esphome/components/i2s_audio_xiao/microphone/i2s_audio_microphone.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.cpp: In member function 'virtual void esphome::i2s_audio_xiao::I2SAudioComponent::setup()':
src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.cpp:15:24: error: 'I2S_NUM_MAX' was not declared in this scope; did you mean 'I2S_NUM_1'?
   15 |   if (next_port_num >= I2S_NUM_MAX) {
      |                        ^~~~~~~~~~~
      |                        I2S_NUM_1
Compiling .pioenvs/esp32s3/src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.cpp.o
In file included from src/esphome/components/i2s_audio_xiao/speaker/../i2s_audio_xiao.h:5,
                 from src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.h:5,
                 from src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
*** [.pioenvs/esp32s3/src/esphome/components/i2s_audio_xiao/i2s_audio_xiao.cpp.o] Error 1
src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.cpp: In static member function 'static void esphome::i2s_audio_xiao::I2SAudioSpeaker::player_task(void*)':
src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.cpp:54:24: error: 'I2S_MCLK_MULTIPLE_DEFAULT' was not declared in this scope; did you mean 'I2S_MCLK_MULTIPLE_512'?
   54 |       .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                        I2S_MCLK_MULTIPLE_512
*** [.pioenvs/esp32s3/src/esphome/components/i2s_audio_xiao/speaker/i2s_audio_speaker.cpp.o] Error 1
========================= [FAILED] Took 75.61 seconds =========================

Note: I am using ESPHome Builder, instead of ESPHome, as ESPHome was not available.

**Reply by formatBCE** [reply]
There's a lot of changes related to i2s in ESPHome 2024.12.
You can use sample code from https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml

**Reply by Richard-Regan** [reply]
Hi,
the yaml you refer to, dos't pass verification.

INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/respeaker-s3.yaml...
INFO Updating https://github.com/esphome/home-assistant-voice-pe@dev
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO3 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO45 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

script: [source /config/esphome/respeaker-s3.yaml:993]
  - id: control_leds
    then: 
      - 
        Couldn't find ID 'wifi_id'. Please check you have defined an ID with that name in your configuration. These IDs look similar: "api_id".
        lambda: !lambda |-
          id(check_if_timers_active).execute();
          if (id(is_timer_active)){
            id(fetch_first_active_timer).execute();
          }
          if (id(improv_ble_in_progress)) {
            id(control_leds_improv_ble_state).execute();
          } else if (id(init_in_progress)) {
            id(control_leds_init_state).execute();
          } else if (!id(wifi_id).is_connected() || !id(api_id).is_connected()){

**Reply by Richard-Regan** [reply]
Please ignore. I think there is an issue in the copy of the yaml.

**Reply by Richard-Regan** [reply]
The problem was I set the wifi settings, i have now replace the origanal code. So how do I specify my wifi ssid and password without breaking the yaml?

**Reply by Richard-Regan** [reply]
Hi, how do I set my wifi details, as the yaml is using wifi_id?

**Reply by formatBCE** [reply]
Check the dashboard file. Just set them. :)

**Reply by vanislman** [reply]
Hello Richard-Regan,
Did you get this working? 
I'm trying to install this Respeaker board with the same HA version you mentioned above. I used the .yaml file mentioned by formatBCE, just added my Wifi info. I can compile the file (with some warnings) and upload it to the board successfully. 
But when I turn on the Respeaker board and add a speaker, I just hear lots of very annoying "scratching" noise.

**Reply by formatBCE** [reply]
> Hello Richard-Regan,
> Did you get this working? 
> I'm trying to install this Respeaker board with the same HA version you mentioned above. I used the .yaml file mentioned by formatBCE, just added my Wifi info. I can compile the file (with some warnings) and upload it to the board successfully. 
> But when I turn on the Respeaker board and add a speaker, I just hear lots of very annoying "scratching" noise.

Did you flash the Respeaker with 48kHz firmware and use 48kHz YAML?

**Reply by vanislman** [reply]
Yes, I flashed the board with 48khz firmware. But I'm not sure if I use the correct YAML? I used the one on this page:
https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml

The only modification I did of that file is to add the 2 wifi statements to the wifi: section:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

**Reply by formatBCE** [reply]
> Yes, I flashed the board with 48khz firmware. But I'm not sure if I use the correct YAML? I used the one on this page:
> https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml
> 
> The only modification I did of that file is to add the 2 wifi statements to the wifi: section:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
> 
> 

Of course it won't work. Respeaker Lite isn't in any way Nabu PE. They have similar, but not identical hardware, and completely different pinout.
Use Respeaker Lite repo, or Koala if you use generic ESP32 board.

**Reply by formatBCE** [reply]
https://github.com/formatBCE/Koala-Satellite
https://github.com/formatBCE/Respeaker-Lite-ESPHome-integration

**Reply by vanislman** [reply]
Thanks so much for your help and for those links. I now followed the instructions in your second link
https://github.com/formatBCE/Respeaker-Lite-ESPHome-integration
and got much further:
- I re-installed the 48K XMOS firmware and used the one on your page, just in case it was different from the Seed Studio one
- I installed the 48K .yaml file (after waiting forever for it to compile on my RPI4)
- I downloaded the new ESP firmware after compiling it
Now the Respeaker Lite boots up properly, connects to Wifi, and I could configure it in HA.
Everything seems to work, except the WAKEWORD:
- The HA setup page for the respeaker shows all standard entities, except the "Wakeword" drop-down is grayed out
- When I run the "Setup voice assistant" wizard, the blue LED blinks and I hear the welcome sound. 
- When I click on "change wake word" the system doesn't show any wake words

Below some screenshots.
![respeaker device configuration](https://github.com/user-attachments/assets/26c2535e-3eed-4ae6-9eed-1b5cc742adc2)
![say wakeup dialog](https://github.com/user-attachments/assets/34ca6048-b1eb-4644-9f21-28d45a41e646)
![change wakeword dialog](https://github.com/user-attachments/assets/66f0a336-004a-4f9a-811b-8a34ddc399c2)

Any idea what I'm still missing?

(Oh, I didn't do any of the soldering you suggested for the buttons. I don't care about the USR button, and the MUTE button seems to work out-of-the-box)

**Reply by formatBCE** [reply]
Yeah, there's some trouble with wake word choosing. I fixed it in Koala, but didn't look into it in regular Respeaker sat. If you want different word, just set it as the only one in YAML and recompile (sorry to hear you have to do it on Pi, it's pain). By default it's using the best one, Ok Nabu. And it should work without wizard.

On the soldering - I recommend doing it. Software mute won't work if you don't, and respeaker_lite component isn't initializing properly if mute button not available. But you can remove related code if you don't want it to be there.
USR button is used to start pipeline without wake word, pause music etc.

**Reply by vanislman** [reply]
Thanks for the fast response again. I just tested with "ok nabu" - and it works! 
No need to change it for now, I just want to do some testing and get some experience with Voice. 
Thanks for all your great work and support !

**Reply by vanislman** [reply]
Hello @formatBCE , can you please tell me how to switch the default wake word in YAML to "Hey Jarvis"? I looked through the file but can't figure out how to change it.

**Reply by formatBCE** [reply]
> Hello @formatBCE , can you please tell me how to switch the default wake word in YAML to "Hey Jarvis"? I looked through the file but can't figure out how to change it.

Looks like on latest ESPHome wizard works, and drop-down with wake words is enabled too..
If it's not - just remove "ok Nabu" code section from Microwakeword config, leave ok Jarvis on first place there, and rebuild.

**Comment by thematrixdev** [comment]
I am trying to add a `media_player` to play the start-up "beep" sound before listening.

```
media_player:
  - platform: i2s_audio_xiao
    id: mp3_player
    dac_type: external
    i2s_dout_pin: GPIO43
    mode: stereo
```

The IDE warns me `This feature is only available with frameworks ['arduino'].`

How to fix or is there any workaround?

Thanks.

**Reply by formatBCE** [reply]
Check the Koala. It has firmware YAML, that you can use as example. https://github.com/formatBCE/Koala-Satellite

**Reply by thematrixdev** [reply]
> Check the Koala. It has firmware YAML, that you can use as example. https://github.com/formatBCE/Koala-Satellite

wow you have made it into a final product!

I am referring to `koala-base.yaml`.
```
media_player:
  - platform: nabu
```
It warns `Platform not found: 'media_player.nabu'.`.

What have I missed?

**Reply by formatBCE** [reply]
External components. There's a lot of things from Nabu PE firmware. ;)
Yup I did :)

**Reply by thematrixdev** [reply]
> Nabu PE

Oh this https://www.home-assistant.io/voice-pe/ 
Recently I have seen it from Youtube.

**Reply by formatBCE** [reply]
> > Nabu PE
> 
> Oh this https://www.home-assistant.io/voice-pe/ 
> Recently I have seen it from Youtube.

Yes. Guys made awesome job, and everyone is riding on their back  :)

**Reply by thematrixdev** [reply]
> > > Nabu PE
> > 
> > 
> > Oh this https://www.home-assistant.io/voice-pe/
> > Recently I have seen it from Youtube.
> 
> Yes. Guys made awesome job, and everyone is riding on their back :)

May you take a look for me please?
The remarked code is from your project.
When they are enabled, after boot, wake word could be identified, but it seems what I said is not recognized.
The playback is some broken noise. Not the sound effect, or TTS.

I am using XIAO ESP32S3, with 3.5mm jack to a speaker.

```
esphome:
  name: esp32s3
  friendly_name: ReSpeakerv3
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended

logger:
  level: VERY_VERBOSE

api:
  encryption:
    key: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: ""

captive_portal:

external_components:
  - source: github://QingWind6/ESPHome_XIAO-ESP32S3
  # - source:
  #     type: git
  #     url: https://github.com/esphome/home-assistant-voice-pe
  #     ref: dev
  #   components:
  #     - aic3204
  #     - audio_dac
  #     - media_player
  #     - nabu

# i2c:
#   - id: internal_i2c
#     sda: GPIO5
#     scl: GPIO6
#     scan: true
    
# audio_dac:
#   - platform: aic3204
#     i2c_id: internal_i2c

i2s_audio_xiao:
  i2s_lrclk_pin: GPIO7
  i2s_bclk_pin: GPIO8
  i2s_mclk_pin: GPIO9

microphone:
  - platform: i2s_audio_xiao
    id: xiao_mic
    adc_type: external
    i2s_din_pin: GPIO44
    pdm: false
    bits_per_sample: 32bit
    channel: left

speaker:
  - platform: i2s_audio_xiao
    id: xiao_speaker
    dac_type: external
    i2s_dout_pin: GPIO43
    mode: stereo

globals:
  - id: to_follow_up
    type: bool

voice_assistant:
  microphone: xiao_mic
  use_wake_word: true
  noise_suppression_level: 0
  auto_gain: 0dBFS
  volume_multiplier: 1
  speaker: xiao_speaker
  # media_player: nabu_media_player
  id: assist
  on_tts_start:
    - lambda: id(to_follow_up) = true;
  on_end:
    - delay: 100ms
    - wait_until:
        not:
          speaker.is_playing:
    - if:
        condition:
          - lambda: |-
              return id(to_follow_up);
        then:
          - lambda: id(assist).set_use_wake_word(false);
        else:
          - lambda: id(assist).set_use_wake_word(true);
    - lambda: id(to_follow_up) = false;
  on_client_connected:
    - voice_assistant.start_continuous:
  # on_wake_word_detected:
  #   - script.execute:
  #       id: play_sound
  #       priority: true
  #       sound_file: !lambda return id(wake_word_triggered_sound);
  #   - delay: 300ms

# media_player:
#   - platform: nabu
#     id: nabu_media_player
#     name: Media Player
#     internal: false
#     audio_dac:
#     speaker:
#     sample_rate: 48000
#     volume_increment: 0.05
#     volume_min: 0.4
#     volume_max: 0.85
#     files:
#       - id: wake_word_triggered_sound
#         file: https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/wake_word_triggered.flac

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO1
    default_transition_length: 0s
    chipset: ws2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0

output:
  - platform: ledc
    id: light_output
    pin: GPIO21
    inverted: true

# script:
#   - id: play_sound
#     parameters:
#       priority: bool
#       sound_file: "media_player::MediaFile*"
#     then:
#       - lambda: |-
#           if (priority) {
#             id(nabu_media_player)
#               ->make_call()
#               .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_STOP)
#               .set_announcement(true)
#               .perform();
#           }
#           if ( (id(nabu_media_player).state != media_player::MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING ) || priority) {
#             id(nabu_media_player)
#               ->make_call()
#               .set_announcement(true)
#               .set_local_media_file(sound_file)
#               .perform();
#           }
```
