### DISCUSSION TITLE
MR60BHA2 Breath-Heartbeat Sensor with Home Assistant | Seeed Studio Wiki

### DISCUSSION THREAD

**Discussion by giscus** [Seeed-Studio/wiki-documents#2346] [Q&A]
# MR60BHA2 Breath-Heartbeat Sensor with Home Assistant | Seeed Studio Wiki

MR60BHA2 Heartbeat mmWave Sensor with Home Assistant

https://wiki.seeedstudio.com/ha_with_mr60bha2/

**Comment by camilogz** [comment]
Hi everyone,

I’ve successfully added the MR60BHA2 to Home Assistant, and the integration is working fine—I can see the device and its entities. However, when I go to the ESPHome page, the device does not appear in the list, so I can’t edit its YAML configuration.

Has anyone else experienced this issue? How can I access the ESPHome configuration for this device? Any help would be greatly appreciated!

Thanks!

**Reply by nfs0619** [reply]
Hi,  

You can try manually adding the device in ESPHome using its IP address:  

1. Go to the **ESPHome** page in Home Assistant.  
2. Click on **"Add Device"** and select **"Add by IP"**.  
3. Enter the IP address of your MR60BHA2 (you can find it in Home Assistant under **Devices & Services**).  

If the issue persists, feel free to contact our technical support team at **[techsupport@seeed.io](mailto:techsupport@seeed.io)** for further assistance.

**Reply by camilogz** [reply]
Hi @nfs0619,

Thanks for your reply! I think I didn’t explain my issue clearly in my original post.

I can see the device and its sensors correctly on the ESPHome page within Home Assistant, as you suggested. However, my issue is that the device does not appear on the ESPHome Builder page, where I would normally be able to edit its YAML configuration.

The reason I need access to the YAML file is that I’d like to add a BMP280 temperature and humidity sensor to the device to make it more versatile. But without access to the ESPHome Builder configuration, I’m unsure how to modify and update the firmware.

Is there a way to manually add the device to ESPHome Builder, or an alternative method to edit its configuration?

Thanks again for your help!

**Reply by nfs0619** [reply]
Thanks for the clarification! Since you're trying to add a BMP280 sensor, please refer to the source code repository below. It contains the ESPHome external components used for this device:
 **https://github.com/limengdu/MR60BHA2_ESPHome_external_components**

You may need to update the configuration based on this repo in order to add your sensor.

If the issue persists, I recommend contacting our technical support team at **[techsupport@seeed.io](mailto:techsupport@seeed.io)**. They will be able to provide more detailed and faster assistance.

**Reply by rotilho** [reply]
@camilogz did you manage to flash it? I have a similar problem, I can't import it to esphome nor flash it through OTA.

My computer is not able recognise it either when plugged.

**Reply by hyacin75** [reply]
> @camilogz did you manage to flash it? I have a similar problem, I can't import it to esphome nor flash it through OTA.
> 
> My computer is not able recognise it either when plugged.

Just got mine, 100% same.  Can't add to ESPHome Builder as C6 isn't supported (even though the docs I found on GitHub make it sound like you should just be able to add it in there) - no option for OTA update, and does not show up as a serial port on my computer using a known good USB-C cable that I literally just used two days ago to serial connect to a Home Assistant Yellow box.

@rotilho , @camilogz  - did you get any further with this?  My device shipped with 2.0 and constantly shows a distance of 0.0m to the 'target', between fixing that, additional people detection, etc., I'd really like to bring it up to 3.5.

@nfs0619 Any chance you could provide some feedback here rather than directing us to email you in silos?  Multiple people having the same issue, and more are sure to come along.  Putting the answers here makes a lot more sense.

**Edit:** As I had ordered three, I just took a brand new one out of the box to see if it made any difference if the device was in a fresh/reset state - but exact same, it does not show up as a serial port in Windows.

**Edit2:** Tried a few more cables just to be sure, and tried basically every USB3 port on this device (which, I'll remind, was doing serial over USB to a Home Assistant Yellow just two days ago) - nada.  This device is 100% NOT exposing a serial port over USB.

**Edit3:** Popped the case open and tried "connecting while holding down the [only button I could see, presumably the 'boot' button]" as I kept seeing everywhere.  Nada.  Then I tried connecting to the OTHER USB-C port that is within the case, and voila, I had a serial port.  Trying to update now with their online tools and they keep failing (advising me to hold down the button while pressing install, which isn't helping), but I'm a big step closer, so fingers crossed.

**Edit4:** Ok, so from [this page](https://wiki.seeedstudio.com/ha_with_mr60bha2/#step-2-preparing-the-kit), the "Web Tool" did not work.  I also found an OTA tool somewhere that did not work.  The "ESPHome Web" combined with the 'factory' bin file from [the repo](https://github.com/limengdu/MR60BHA2_ESPHome_external_components/releases) _seems_ to have worked though.  I've added the 'new' one, it's not showing any devices or entities yet though - iirc this took some time with the first one too.  I flashed the first one with the OTA image hoping it wouldn't blow away my settings, and now HA isn't seeing it at all, so I think I may need to crack it back open, 'prepare for first use', flash the factory image, and then connect to the WiFi to get it reconnected to my network.

**Edit5:** Device "2" finally produced a 'device' and entities, and confirmed, it's running 3.5 -

![image](https://github.com/user-attachments/assets/78c3701f-70b3-4966-ab6a-f712d4892598)

**Edit6:** Connecting device "1" to the PC to reflash it, the serial device keeps appearing and disappearing - I think it's in a bootloop.  So **I would not advise trying to use the OTA firmware to avoid redoing the config!**  I'm unscrewing it from the bottom case now to do a 'hold the button and power on', and hopefully then it will be stable and I can start fresh.

**Edit7:** Device "2" was working for a few minutes after a reboot but is just randomly going and staying unavailable.  And I can't seem to get device "1" out of what looks like a bootloop no matter how long I hold the button or at what point ... so at this point, I'd say "live with the 2.0 firmware it shipped with if you can, or put the device on a shelf for a few weeks or months to avoid bricking it" 😞 

**Edit8:** Now I'm not even getting a disappearing serial port from device "1", just nothing - so I'll again reiterate, be very careful going down this path, or do not go down it at all without guidance (and replacement justification if things go sideways) from Seeed.

**Edit9:** Ok, so what I _thought_ was a reset button on the large board, I guess was not a reset button.  There are two tiny little metal circles to the left and right of the USB-C port that is on the ESP32C6 board (the small one you have to open the case to see) ... one has a small B, and one a small R.  These are in fact buttons, just very difficult to operate ones.  The B, is the 'boot' button.  Holding that down with the tip of a tiny screwdriver, and then applying power to the ESP32C6 board directly (with what was also a console cable as the other end was my PC) enabled a stable serial port, and I was able to 'prepare for first use' and then 'install' the 3.5 image.  I doubt it will be any more stable than the other board I flashed with 3.5, but I'm happy it doesn't seem to be in a boot loop anymore.

**Edit10** (day 2): so I have, like, all the sensors here, two types of Seeed mmWave, three types of Screek mmWave sensors ... I'd intended to cannibalize/convert some of the older 24 GHz Seeed ones I have to 60 GHz but that didn't work out.  What I _was_ able to steal from them though, is WiFi antennas!  They do seem to be plentiful and cheap on Amazon, but I figured if I've got some here, already of roughly the right length, and doing nothing, why not try them out?  So I've gone back to the 3.5 firmware that seems to have bigger WiFi issues than the 2.0 firmware, but with an antenna now.  So far, so good.  It's also added "person information" (detected/not) and "target number" (presumably number of people detected) which 2.0 didn't have.  "Distance to detection object" is still showing as unknown.  Fingers crossed the antenna improves what looks a lot like connectivity issues (sensors all going 'unknown', frequently, and for extended periods of time). 

**Edit11:** For anyone going down the same road with the antenna, it _seems_ the connector is U.FL/IPEX/MHF1 (not IPEX4 or MHF4)

**Edit12** (day 3): IPEX / "IPEX G1" confirmed, I ordered [these](https://www.amazon.ca/dp/B07W4KVCMB?ref=ppx_yo2ov_dt_b_fed_asin_title) and it snapped on np.  Generally though, these running 3.5 is "WOW bad" ... two of them sitting ~1.5' from me, with the antenna, frequent disconnects from HA, and now they're saying "yep, there is a person there" and they're connected, I can turn the light on and off, but they show no heart rate or breathing.  And I do have them at different angles so as to not conflict.  I'm going to try a longer test with them even more spread out (basically 0, 50 and 110 degrees or so), one with the original 2.0 and the new antenna, one 3.5 old/kit antenna, one 3.5 no antenna, and see if I can find anything that is stable.

**Edit13:** I hope all this info is useful for someone at some point in the future, lol!  Upon opening and connecting my 3rd unit without touching the firmware, it seems firmware 2.0 does in fact have the additional items I thought it did not - maybe they just weren't discovered yet or something when I added the cards to a dashboard last time.  All three show the same available data though -

![image](https://github.com/user-attachments/assets/3a0f1303-3af8-4909-89a3-f84ca70489e6)

**Edit14:** 3.5 firmware with the antenna from the "presence detection kit" flatlined first, and quick ... I haven't moved, the other two are still tracking my heartrate fine, but it's gone to 0 and past experience says it will stay there until a restart -

![image](https://github.com/user-attachments/assets/c877d7ec-daf0-4106-8c8a-866d3b3ef438)

**Edit15:** The only one that seems to pick back up and carry on after I leave and come back is the 2.0 unit -

![image](https://github.com/user-attachments/assets/c9ec5ee5-da6b-4150-a715-0ece3d6649a2)

They're all still connected, I can toggle their lights - but the two 3.5 units will not register any vitals.  I'll swap positions and/or antennas (in case they're causing any kind of interference, primarily) and see if anything changes.

**Reply by nfs0619** [reply]
Hi @hyacin75 ，

Thanks so much for taking the time to document your process in such detail—this kind of real-world testing and feedback is incredibly valuable!

We welcome you to share your experience on our community forum: [https://forum.seeedstudio.com/](https://forum.seeedstudio.com/). There, you'll find more users who enjoy discussing topics like this, and it’s a great place to dive deeper into troubleshooting and share updates.

Really appreciate your effort and hope things continue to improve with your setup!

**Reply by hyacin75** [reply]
> Hi @hyacin75 ，
> 
> Thanks so much for taking the time to document your process in such detail—this kind of real-world testing and feedback is incredibly valuable!
> 
> We welcome you to share your experience on our community forum: https://forum.seeedstudio.com/. There, you'll find more users who enjoy discussing topics like this, and it’s a great place to dive deeper into troubleshooting and share updates.
> 
> Really appreciate your effort and hope things continue to improve with your setup!

Oh, amazing, I am able to create threads there now!  Initially I was not and joined in [an existing thread](https://forum.seeedstudio.com/t/about-the-xiao-category/251343/5) to ask about it where other users with the same issue were doing the same.  It seems I am able to now though, so that's great, I'll see what I can find there!  Thanks!!  😄

**Comment by corgan2222** [comment]
HA 2025.6.1
ESPHome: 2025.6.1

will crash and boot loop because of problems with i2c.
Add "scan: false" to i2c

full working code:

```
esphome:
  name: seeedstudio-mr60bha2-kit-8549b0
  friendly_name: seeedstudio-mr60bha2-kit-8549b0
  # project:
  #   name: "seeedstudio.mr60bha2_kit"
  #   version: "3.5"
  platformio_options:
    board_upload.maximum_size: 4194304
  min_version: "2025.6.1" # Fix logger compile error on ESP32-C6 esphome#6323


esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "yyy"
    
packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml    

i2c:
  - id: bus_a
    sda: GPIO22
    scl: GPIO23
    scan: false 

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1  

seeed_mr60bha2:
  id: my_seeed_mr60bha2
  uart_id: uart_bus


binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information" 

sensor:
  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 1s  
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
    num_targets:
      name: "Target number"      
```

packages:
  wifi: !include common/wifi.yaml

```
wifi:
  networks:
  - ssid: "ssid"
    password: "!!!!"
    
  reboot_timeout: 2min      


```

packages:
  device_base: !include common/device_base.yaml    

```
debug:
  update_interval: 30s

logger:  
  level: DEBUG

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""  

  - platform: uptime
    name: "Uptime Sensor"   


time:
  - platform: homeassistant
    id: homeassistant_time


binary_sensor:
  - platform: status
    name: "Status"  

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"    
  - platform: version
    name: "Version"   
  - platform: debug
    reset_reason:
      name: "Reset Reason"       

button:
  - platform: restart
    name: "Restart"         
```
