### DISCUSSION TITLE
24GHz mmWave for XIAO | Seeed Studio Wiki

### DISCUSSION THREAD

**Discussion by giscus** [Seeed-Studio/wiki-documents#802] [Q&A]
# 24GHz mmWave for XIAO | Seeed Studio Wiki

Getting started with Seeed Studio 24GHz mmWave for XIAO

https://wiki.seeedstudio.com/mmwave_for_xiao/

**Comment by harmfulmushroom** [comment]
The product page states that this sensor works in HomeAssistant and ESPHome, but I'm struggling to get this device up and running. Is there any documentation which can point me in the right direction for doing that?

**Reply by nlitz88** [reply]
I just spent the last hour putting together this yaml file using a couple of different pages I found. I used a XIAO ESP32C3 and the XIAO mmWave board (which seems to have an [LD2410 on board, which is already supported by ESPHome](https://esphome.io/components/sensor/ld2410)).

I basically just had to figure out which GPIO pins on the XIAO ESP32C3 were needed for the UART connection to the XIAO mmWave board (referencing the [mmWave board's page](https://wiki.seeedstudio.com/mmwave_for_xiao/#hardware-overview) and the [XIAO ESP32C3's page](https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/#pinout-diagram), and then I just followed the [LD2410 ESPHome documentation](https://esphome.io/components/sensor/ld2410).

Here's an example with just presence detection (and no other fancy details) to get you started:

```
esphome:
  name: xiao-esp32c3
  platformio_options:
   board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    platform_version: 5.4.0

# Enable logging
logger:
 hardware_uart: UART0

# Enable Home Assistant API
api:

ota:

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiao-Esp32C3 Fallback Hotspot"
    password: "fallback"

# Per https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/#pinout-diagram and https://wiki.seeedstudio.com/mmwave_for_xiao/#hardware-overview
uart:
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600

# Example configuration entry from https://esphome.io/components/sensor/ld2410
ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
```

For more detailed information from the LD2410 living on the XIAO mmWave board, take a look at that ESPHome link I have above--they have all kinds of additional sections you can add to the YAML for more details and controls.

Hope this helps :)

**Reply by harmfulmushroom** [reply]
Thanks for the pointers! Not sure why I was struggling so much with this one, but your code definitely got me pointed in the right direction. All you really have to do is add this to the end under binary_sensor to make presense sensing work:

```
  - platform: gpio
    pin: GPIO10
    name: gpio out pin presence
    device_class: presence

Full line is just this:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO10
    name: gpio out pin presence
    device_class: presence
```
It's way too sensitive and prone to false positives (not to mention blank entries) but with this I can start addressing those issues one step at a time. Thanks again!

**Reply by nlitz88** [reply]
Glad to hear the yaml helped a bit!

> It's way too sensitive and prone to false positives

After playing around with my own setup a bit, I also ran into these same problems. Keep me posted if you are able to find some kind of tuning/calibration that improves the output.

**Reply by harmfulmushroom** [reply]
I ended up doing a little more research and found someone elses code for another board here: [https://community.home-assistant.io/t/ld2410-mmwave-sensor-no-longer-recognised-in-esphome/616646/11](url)

Changed the UART pins accordingly and updated to match our board, and so far it's been pretty stable! Hopefully this helps some!

```
esphome:
  name: esphome-web-843228
  friendly_name: Living Room mmWave

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    platform_version: 5.4.0
 
# Enable logging
logger:
  level: WARN
  baud_rate: 0
 
# Enable Home Assistant API
api:
  encryption:
    key: "(API Key Here)"
 
ota:
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
uart:
  id: uart01
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart01
  id: ld2410_comp
 
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
 
sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

**Reply by MatthewJeffson** [reply]
Wow! @harmfulmushroom That is amazing! Thank you so much!

**Comment by Motya-HA** [comment]
For some reason I can't get work some entities (in itlic and Strikethrough): 

sensor:
  - platform: ld2410
    *~~light:
      name: light~~*
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    *~~g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy~~*

**Reply by Motya-HA** [reply]
I figured  it out - it work only in engineering mode.
Does someone understand the point of "light" entity? I do not think this HW has light sensor

**Comment by shubhamkastwar1** [comment]
Heay, this works with zones 

```
uart:
  id: ld2410_uart
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600

# Example configuration entry from https://esphome.io/components/sensor/ld2410
ld2410:
  uart_id: ld2410_uart

number:
  - platform: ld2410
    timeout:
      name: Radar Timeout
    max_move_distance_gate:
      name: Radar Max Move Distance
    max_still_distance_gate:
      name: Radar Max Still Distance
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
  # Setting ending of zone 1 occupancy
  - platform: template
    name: "Radar End Zone 1"
    id: radar_z1_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 10
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

  # Setting ending of zone 2 occupancy
  - platform: template
    name: "Radar End Zone 2"
    id: radar_z2_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 36
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

  # Setting ending of zone 3 occupancy
  - platform: template
    name: "Radar End Zone 3"
    id: radar_z3_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 100
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

#Occupancy sensor
binary_sensor:
  - platform: ld2410
    has_target:
      name: Radar Target
      id: radar_has_target
    has_moving_target:
      name: Radar Moving Target
    has_still_target:
      name: Radar Still Target
  ## Set Up Radar Zones Based On Distance
  - platform: template
    name: "Radar Zone 1 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && (id(radar_detection_distance).state < id(radar_z1_end).state)) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Radar Zone 2 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && ((id(radar_z1_end).state < id(radar_detection_distance).state) && (id(radar_detection_distance).state < id(radar_z2_end).state))) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Radar Zone 3 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && ((id(radar_z2_end).state < id(radar_detection_distance).state) && (id(radar_detection_distance).state < id(radar_z3_end).state))) {
        return true;
      } else {
        return false;
      }

#Exposes configuration and status sensors
sensor:
    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    # lambda: |-
    #  return (id(cpu_speed));
    entity_category: "diagnostic"
    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"
    #Device Temperature
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 60s
    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: ld2410
    moving_distance:
      name: Radar Moving Distance
      id: moving_distance
    still_distance:
      name: Radar Still Distance
      id: still_distance
    moving_energy:
      name: Radar Move Energy
    still_energy:
      name: Radar Still Energy
    detection_distance:
      name: Radar Detection Distance
      id: radar_detection_distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

#Exposes control buttons
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

  - platform: ld2410
    factory_reset:
      name: "Factory Reset Radar"
    restart:
      name: "Restart Radar"
    query_params:
      name: query params

#Exposes control switches
switch:
  - platform: ld2410
    bluetooth:
      name: "Radar Control Bluetooth"
      id: radar_bluetooth
    engineering_mode:
      name: "Radar Engineering Mode"
time:
  - platform: sntp
    id: time_sntp

#Radar firmware version
text_sensor:
  - platform: ld2410
    version:
      name: "Radar Firmware Version"
#Set distance resolution - 0.75m or 0.2m
select:
  - platform: ld2410
    distance_resolution:
      name: "Radar Distance Resolution"
```

**Reply by shubhamkastwar1** [reply]
I am trying to figure out how this below function will work with C3 
lambda: |-
return (id(cpu_speed));

**Comment by FutureSharks** [comment]
Does anyone have a working ESPHome config for this module and the Xiao ESP32 C6? 🙏

**Reply by limengdu** [reply]
https://github.com/limengdu/MR60BHA2_ESPHome_external_components/blob/f875eba14198a61f13d39182ba6c2558b7401511/example/mr60bha2.yaml#L17
Please refer to the procedure for millimetre wave radar.

**Reply by FutureSharks** [reply]
Thanks @limengdu but it still doesn't work, all the sensors stay unknown. I have it working on a Xiao C3 fine using pins GPIO05/04 and baud rate 115200. I tried those same pins with the config you linked to but no luck. Tried setting the parity and stop bits (not required on the C3) but still no luck. Is there something specific with the UART config on the C6 that I need?

**Reply by limengdu** [reply]
Radar is also currently reporting news through UART. We haven't encountered any problems while developing it, so we suggest you check your procedure by referring to the UART configuration of the radar. If you still can't solve it, I suggest you finish describing your problem and yaml code in our forum or ESPHome's forum and we'll take a look at it together. This doesn't rule out the possibility that it could be an ESPhome issue, ESPHome has not officially released support for the ESP32C6 chip yet.

**Reply by FutureSharks** [reply]
I got it working after asking in the Seeed forums, the pin numbers were wrong. This is working configuration for the Xiao ESP32 C6:

```yaml
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

logger:
  level: DEBUG

uart:
  baud_rate: 256000
  rx_pin: 2
  tx_pin: 21

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
```
